name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Checking out code..."

      - name: Build application
        run: echo "Starting build process..."

      - name: Create artifact
        run: echo "Hello from CI/CD!" > app.txt

      - name: Verify build
        run: |
          cat app.txt
          echo "Build completed successfully"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: |
          echo "Running tests..."
          echo "All tests passed!"
